name: latesttag

on:
  release:
    types: [released]

jobs:
  tagrelease:
    name: Tag release to latest tag
    steps:
    - name: Run latest-tag
      uses: EndBug/latest-tag@latest
      with:
        tag-name: latest
